### ISSUE TITLE
process.stdout, process.stderr streams

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-core#10]
By default the process shim does not include these features.

But if we made them getters that conditionally were to load in the stream functionality only as needed and then block the streams on the first read / first write on that dynamic import that seems like it would provide a way to offer the functionality without bloat while still supporting the use cases.

**Comment by guybedford** [comment]
The problem with process getters is they don't work for the named exports form, which makes me weary of implementing this right now, especially given there hasn't been further implementation pressure here.

Will keep this open for if it comes up in future, but it's not currently on the list.

**Comment by Mesteery** [comment]
I don't think this should be closed since it is still not supported in browser.

**Comment by guybedford** [comment]
I also forgot about the named exports getter issue here for Deno too.

That is also a case where embedding the implementation as a mock of the start of the stream itself would help instead of using getters.

**Comment by Mesteery** [comment]
I just realized that stdin, stdout and stderr don't need a getter, because they don't seem to require higher permissions.

**Comment by guybedford** [comment]
Oh really? Are you sure? I was very much under the impression a permission was needed. In that case we should just export the full implementation from the start.

**Comment by Mesteery** [comment]
```ts
Deno.isatty(Deno.stdout.rid);
Deno.isatty(Deno.stderr.rid);
Deno.isatty(Deno.stdin.rid);
Deno.consoleSize(Deno.stdout.rid);
Deno.consoleSize(Deno.stderr.rid);
Deno.stdout.writeSync(new TextEncoder().encode('hello'));
Deno.stderr.writeSync(new TextEncoder().encode('hello'));
Deno.stdin.readSync(new Uint8Array(10));
Deno.stdin.close();
Deno.stdout.close();
Deno.stderr.close();
```
```
Check file:///C:/Users/me/workspace/_experiments/denode/a.ts
hellohelloa
```

**Comment by guybedford** [comment]
Great, I'm happy to leave these unimplemented in the browser for now. Let's close this actually.

**Comment by promentol** [comment]
I am trying to port a node.js project to Cloudflare web workers, and our node.js polyfill plugin uses this library.
We have calls to process.stdout.write and process.stderr.write, is there any workaround we can do support this?
I am happy to contribute it, just need permission and some direction

**Comment by promentol** [comment]
I am imagining to point them to console.log, console.prompt and console.errors
