### ISSUE TITLE
'/npm:@jspm/core@2/nodelibs/url' does not provide an export named 'fileURLToPath'

### ISSUE THREAD

**Issue by zhoukekestar** [jspm/jspm-core#13]
Can't import package `yargs` by `import('https://jspm.dev/yargs')`;

with fellow error
```
Uncaught (in promise) SyntaxError: The requested module '/npm:@jspm/core@2/nodelibs/url' does not provide an export named 'fileURLToPath'
```

**Comment by zhoukekestar** [comment]
This code works for me
```js
const url = require('@jspm/core/nodelibs/url');
const fileURLToPath = require('file-uri-to-path');

url.fileURLToPath = fileURLToPath;
module.exports = url;
```

**Comment by guybedford** [comment]
@zhoukekestar glad you worked out the patching workflow here! And with import maps these patches become easy too.

I will released an update with this feature with the next jspm core release, and leave this open until then.

**Comment by guybedford** [comment]
This is now implemented on the main branch, and will be included in the next release.
