### ISSUE TITLE
Feature: inspector

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-core#30]
Tracking issue for "inspector" support (if any?).

**Comment by Aslemammad** [comment]
Hey @guybedford, I hope you're doing well!
I checked out jspm, and I'm really interested in contributing!
I've got a question?
How can I help to go through the issue and other issues? What's the common formula you used to solve issues in jspm-core?

**Comment by guybedford** [comment]
@Aslemammad thank you for showing an interest in contributing!

There are two ways to go about it - (1) look up issues and see where you can start working on something. If you are specifically interested in JSPM core issues, the way to do it would be to pick a feature, write an example Node.js module using that feature, then see if you can run that same module in Deno or browsers using the generated JSPM generator import map for using that core library.

For example, async_hooks or http.

(2) would be to try more advanced scenarios like running particular Node.js libraries or applications in browsers or Deno, seeing where they break, then working through the issues carefully, but would certainly be a harder approach as debugging can get tricky.

**Comment by Aslemammad** [comment]
Thank you @guybedford, I appreciate it. I'm going to see if I can do something about this issue and others!
