### ISSUE TITLE
Deno support for Node.js server builtins

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-core#4]
Currently all the builtins here are browser-based.

It would be useful for full Deno support to use a Deno Node.js shim in the Deno cases.

The main blocker for implementing this is ensuring that https://github.com/denoland/deno/tree/master/std/node has better compatibility than the current "browserify" browser libs.

**Comment by pavel-kolesnikov** [comment]
rethinkdb of Deno needs Node.js net module support...

**Comment by guybedford** [comment]
Deno versions are now on main. @pavel-kolesnikov support for a library like "net" would be worth posting to Deno directly for support in their compatibility layer at https://deno.land/std@0.103.0/node.

**Comment by pavel-kolesnikov** [comment]
> 
> 
> Deno versions are now on main. @pavel-kolesnikov support for a library like "net" would be worth posting to Deno directly for support in their compatibility layer at https://deno.land/std@0.103.0/node.

already, actually.
https://github.com/denoland/deno_std/issues/666

**Comment by guybedford** [comment]
@pavel-kolesnikov there's your chance to contribute :)

**Comment by brillout** [comment]
Does this mean we can now use Node.js libraries in Deno?

**Comment by guybedford** [comment]
@brillout yes, passing `env: ['deno']` to jspm/generator then using `generator.traceInstall(entry.js)` can be used to construct an import map that will support Deno execution for Node.js applications. That said Deno still has patchy support for Node.js builtins so this still breaks down fairly quickly for most apps. See eg https://github.com/jspm/generator/blob/main/test/deno/self.test.js where jspm/generator generates an import map to run itself in Deno using the Node.js compat layer.

**Comment by brillout** [comment]
@guybedford

So lovely.

I guess I can also have a Deno app with only a single Node.js dependency?

> Deno still has patchy support for Node.js builtins

Is there a place where progress can be tracked?

I can see Deno to hit mainstream once it has seemless support for Node.js tools. E.g. Vite and vite-plugin-ssr (shameless plug I'm the author of the latter :-))

**Comment by guybedford** [comment]
> I guess I can also have a Deno app with only a single Node.js dependency?

Right exactly, you can just install into the map the Node.js packages you need.

There's JSPM Discord, Twitter, and then the repos here to watch. The generator project is where most of this is happening.

Seamless support for Node.js server tools will only come with proper http / https / http2 support in Deno... a good place to contribute as there is no one working on that right now so unfortunately that's the blocker on a lot of this.

**Comment by brillout** [comment]
Ok thanks for your reply and everything you're doing 😊.
