### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by jimmywarting** [jspm/jspm-core#47]
Just experimented with node's http loader along with jspm. 

I tried to load a package and `self` isn't defined in nodejs
https://github.com/jspm/jspm-core/blob/12946895f998ffd258d2701fd64171a06f48c9d0/src-browser/util.js#L29-L30

Better would be to use globalThis instead of self or perhaps none at all.

**Comment by guybedford** [comment]
These are browser builtins so they aren't designed to run in Node.js.

For Node.js support, run the generator with the "node" environment condition and use the import maps loader instead.

**Comment by jimmywarting** [comment]
Didn't find any "node" env option on https://generator.jspm.io

wouldn't it be good to use globalThis anyway?

**Comment by guybedford** [comment]
Give me a day and it’ll be back!

**Comment by guybedford** [comment]
The "node" option is now back, along with a "deno" one as well.

**Comment by jimmywarting** [comment]
thanks
