### ISSUE TITLE
New Node.js builtins

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-core#5]
The following new Node.js builtins are currently unimplemented:

- [ ] async_hooks
- [x] diagnostics_channel
- [ ] http2
- [ ] inspector
- [x] perf_hooks
- [x] stream/web
- [ ] trace_events
- [ ] wasi

This is a tracking issue pending further investigation into support of a specific builtin via its own issue.

Requests / feedback / offers for contributions welcome here.

**Comment by benkeil** [comment]
Any news on this?

**Comment by guybedford** [comment]
@benkeil anything in particular you are looking to support? Work here should be use case driven.

**Comment by benkeil** [comment]
At least the http2 Module mentioned in the linked issue.

**Comment by guybedford** [comment]
Would you be interested in submitting a PR?

**Comment by benkeil** [comment]
In generel yes, but to be honest I have absolutely no idea where to start and what todo.

**Comment by guybedford** [comment]
The starting point is the same as for browserify - we just need a version of the library that will run in the browser. For example, this is how the http shim looks - https://github.com/jhiesey/stream-http/blob/master/index.js.

The https shim builds on top of that and looks like this - https://github.com/substack/https-browserify/blob/master/index.js.

In jspm core we just pull these third party packages through directly.

The process for HTTP/2 would thus be the same, to create an API on top of http like https does, that then exposes the API that HTTP/2 provides which is as described here - https://nodejs.org/dist/latest-v14.x/docs/api/http2.html.

Therefore, the basic starting point would likely be something like:

```js
var http = require('http');

var http2 = module.exports;

http2.createSecureServer = function (options) {
  // ... use options to create an http server, ignoring unnecssary ones liek keys etc
}

http2.createServer = function ...
```

and publishing that as its own package to npm.

Once that exists, we can throw it in jspm core here and support HTTP/2.

**Comment by guybedford** [comment]
diagnostics_channel, perf_hooks are in thanks to @JayaKrishnaNamburu. stream/web is in thanks to @Mesteery. Moving to separate tracking issues further.
