### ISSUE TITLE
Uncaught (in promise) TypeError: process.on is not a function

### ISSUE THREAD

**Issue by puria** [jspm/jspm-core#55]
I was used to consume my library directly from jspm.dev
`import { zencode_exec } from "https://jspm.dev/zenroom@next";`
without problem, but since `@jspm/core@2.0.0-beta.9` got this error on `process` shim/polyfill module:
```
Uncaught (in promise) TypeError: process.on is not a function
```

the solution was switching to explicitly use importmap with @jspm/core@**2.0.0-beta.8**:

```js
    <script type="importmap">
{
  "imports": {
    "zenroom": "https://ga.jspm.io/npm:zenroom@2.2.0/dist/main/index.js"
  },
  "scopes": {
    "https://ga.jspm.io/npm:zenroom@2.2.0/": {
      "buffer": "https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.8/nodelibs/browser/buffer.js",
      "crypto": "https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.8/nodelibs/browser/crypto.js",
      "fs": "https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.8/nodelibs/browser/fs.js",
      "path": "https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.8/nodelibs/browser/path.js",
      "process": "https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.8/nodelibs/browser/process.js"
    }
  }
}
    </script>
```

If can help can provide reproducible code or examples ;p
Just let me know!

**Comment by guybedford** [comment]
Thank you for sharing! I've posted a fix in https://github.com/jspm/jspm-core/pull/56, will create a new release soon.
