### ISSUE TITLE
Beta 11 Release

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-core#57]
Just noting the next release will be posted with https://github.com/jspm/jspm-core/commit/2df1f2b04d3be6ca5af20061e3c2c243ff212b90 and https://github.com/jspm/jspm-core/commit/2bc1f50c4d626eb5e45319a897a6d1bcce7e4ed3 very soon.

@Mesteery is there anything else worth including or considering for this release?

**Comment by Mesteery** [comment]
Except memfs (https://github.com/streamich/memfs/commit/eed6bbfa2fc310639974ed9e163876ff8253b321) which could be updated, I don't see what else to include.

**Comment by guybedford** [comment]
Thanks for that one!
