### ISSUE TITLE
`crypto` uses `eval` in `Script`

### ISSUE THREAD

**Issue by imranbarbhuiya** [jspm/jspm-core#83]
Hi, thanks for this awesome package. I'm using it in https://github.com/imranbarbhuiya/esbuild-plugins-node-modules-polyfill to polyfill nodejs inbuilt modules for browser environments. But some users are having issue with present of direct-eval in `crypto` and `vm` code. https://github.com/imranbarbhuiya/esbuild-plugins-node-modules-polyfill/issues/31. Modern bundlers optimizes and treeshakes lots of unused codes but using when `eval`, bundlers can't do those optimizations [ref from esbuilt](https://esbuild.github.io/content-types/#direct-eval). So I'm suggested instead of using direct eval, use one of the suggested alternatives present in  https://esbuild.github.io/content-types/#direct-eval. using `(0, eval)('x')` is generally used in many codebases so this can be used. I can create a pr to fix the issue but which file should I edit? because the crypto file seems like an autogenerated file. Also I can't find `Script` or `createScript` present in `node:crypto` so why these 2 fns are present here?

**Comment by JayaKrishnaNamburu** [comment]
I didn't completely get what you are referring to. But, the `jspm-core` is usig `crypto-browserify` module to polyfill this for browsers.
You can check it here https://github.com/jspm/jspm-core/blob/main/src-browser/crypto.js
If you have a reproduction of the error, that helps it narrowing it down 👍

**Comment by imranbarbhuiya** [comment]
Thanks for the reply. I found the eval. It's present in `vm-browserify` https://github.com/browserify/vm-browserify/blob/033537b20cec686adecaa4dde61c91134d59bc41/index.js#L110 and it's used in crypto here https://github.com/browserify/crypto-browserify/blob/460a13b5bf1e4ea60dc995906ba0543f7933a32b/example/bundle.js#L200. For now, I've added a replace `eval(` with `(0, eval)(` in my package https://github.com/imranbarbhuiya/esbuild-plugins-node-modules-polyfill/blob/dad802e9a8ba88b32ba0c58c0fa6427dda2c0dc2/src/lib/plugin.ts#L23 and it's working. I'll close this issue as it's not related to this package.
