### ISSUE TITLE
add `randomUUID` and `randomValues` to `crypto` module

### ISSUE THREAD

**Issue by imranbarbhuiya** [jspm/jspm-core#84]
`crypto-browserify` don't have `randomUUID` and `randomValues`. And the package is no longer maintained. I'm not sure if you'll add additional stuff here so lmk. Also if u allow additional stuff, can I port https://github.com/browserify/crypto-browserify/pull/215 pr here?

**Comment by guybedford** [comment]
@imranbarbhuiya I'd recommend creating your own fork of crypto browserify in this case, and I would be more than happy to reference your fork instead of crypto-browserify in JSPM core.

**Comment by guybedford** [comment]
This is now implemented in https://github.com/jspm/jspm-core/pull/99, thanks for reporting.
