### ISSUE TITLE
Get error message: Unexpected response from the npm registry 

### ISSUE THREAD

**Issue by limichange** [jspm/jspm-core#92]
I've encountered an issue regarding our JavaScript package. You can find the package at https://www.npmjs.com/package/@pathintegral/amplitude-analytics-browser.

It's also accessible on StackBlitz and CodeSandbox for easy integration into our projects.

We can visit it on [unpkg](https://www.unpkg.com/browse/@pathintegral/amplitude-analytics-browser@1.1.1/dist/).

However, when trying to request the build API, I receive the following error message:

https://api.jspm.io/build/@pathintegral/amplitude-analytics-browser@1.1.1

```
{"error":"Unexpected response from the npm registry, it may be experiencing issues!"}
```

https://generator.jspm.io/  error

```
Error: Unable to request the JSPM API for a build of @pathintegral/amplitude-analytics-browser@1.1.1, with error: Unexpected response from the npm registry, it may be having issues!.
```
Could this issue be related to npm? Thanks.

**Comment by guybedford** [comment]
Thanks for posting, this should be working now.
