### ISSUE TITLE
what are the chunk-*.js files?

### ISSUE THREAD

**Issue by fyears** [jspm/jspm-core#96]
Hi I would like to polyfill for browser and I come across your repo here.

It seems great. But may I ask what are the mysterious chunk-*.js files in browser folders?

**Comment by guybedford** [comment]
Glad to hear you have a use case for it. It's not as heavily maintained as it should be right now, but I do hope to get to improvements in due course. This package is built and optimized, so shared libraries between separate builtins which can be imported individually are grouped into chunks.
